<div class="panel panel-default">
	<div class="panel-heading">推广数据</div>
	<div class="panel-body">
		<form class="form-horizontal" method="get" action="#">
			<div class="form-group">
				<label>期号</label>
				<?php
				echo $this->tag->textField(array(
					'no',
					'value' => $this->getQuery('no'),
					'class' => 'form-control'
				));
				?>
			</div>
			<div class="form-group">
				<div class="col-xs-6 col-sm-4 col-md-2">
					<label>开奖号码</label>
				</div>
				<div class="col-xs-6 col-sm-4 col-md-2">
				<?php
				echo $this->tag->textField(array(
					'num1',
					'value' => $this->getQuery('num1'),
					'class' => 'form-control',
					'placeholder' => '1号'
				));
				?>
				</div>
				<div class="col-xs-6 col-sm-4 col-md-2">
				<?php
				echo $this->tag->textField(array(
					'num2',
					'value' => $this->getQuery('num2'),
					'class' => 'form-control',
					'placeholder' => '2号'
				));
				?>
				</div>
				<div class="col-xs-6 col-sm-4 col-md-2">
				<?php
				echo $this->tag->textField(array(
					'num3',
					'value' => $this->getQuery('num3'),
					'class' => 'form-control',
					'placeholder' => '3号'
				));
				?>
				</div>
				<div class="col-xs-6 col-sm-4 col-md-2">
				<?php
				echo $this->tag->textField(array(
					'num4',
					'value' => $this->getQuery('num4'),
					'class' => 'form-control',
					'placeholder' => '4号'
				));
				?>
				</div>
				<div class="col-xs-6 col-sm-4 col-md-2">
				<?php
				echo $this->tag->textField(array(
					'num5',
					'value' => $this->getQuery('num5'),
					'class' => 'form-control',
					'placeholder' => '5号'
				));
				?>
				</div>
				<div class="col-xs-6 col-sm-4 col-md-2">
				<?php
				echo $this->tag->textField(array(
					'num6',
					'value' => $this->getQuery('num6'),
					'class' => 'form-control',
					'placeholder' => '6号'
				));
				?>
				</div>
				<div class="col-xs-6 col-sm-4 col-md-2">
				<?php
				echo $this->tag->textField(array(
					'num7',
					'value' => $this->getQuery('num7'),
					'class' => 'form-control',
					'placeholder' => '7号'
				));
				?>
				</div>
				<div class="col-xs-6 col-sm-4 col-md-2">
				<?php
				echo $this->tag->textField(array(
					'num8',
					'value' => $this->getQuery('num8'),
					'class' => 'form-control',
					'placeholder' => '8号'
				));
				?>
				</div>
				<div class="col-xs-6 col-sm-4 col-md-2">
				<?php
				echo $this->tag->textField(array(
					'num9',
					'value' => $this->getQuery('num9'),
					'class' => 'form-control',
					'placeholder' => '9号'
				));
				?>
				</div>
				<div class="col-xs-6 col-sm-4 col-md-2">
				<?php
				echo $this->tag->textField(array(
					'num10',
					'value' => $this->getQuery('num10'),
					'class' => 'form-control',
					'placeholder' => '10号'
				));
				?>
				</div>
			</div>
			<div class="form-group">
				<label>日期</label>
				<?php
				echo $this->tag->textField(array(
					'date',
					'value' => $this->getQuery('date'),
					'class' => 'form-control'
				));
				?>
			</div>
			<div class="input-group">
				<span class="input-group-btn">
					<button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
				</span>
			</div>
		</form>
	</div>
	<table class="table">
		<thead>
			<tr>
				<th>期号</th>
				<th>开奖号码</th>
				<th>日期</th>
			</tr>
		</thead>
		<tbody>
			<?php
			foreach ($page->items as $item) {
			?>
				<tr>
					<td><?= $item->no ?></td>
					<td><?= $item->num1 ?>,<?= $item->num2 ?>,<?= $item->num3 ?>,<?= $item->num4 ?>,<?= $item->num5 ?>,<?= $item->num6 ?>,<?= $item->num7 ?>,<?= $item->num8 ?>,<?= $item->num9 ?>,<?= $item->num10 ?></td>
					<td><?= $item->date ?></td>
				</tr>
			<?php } ?>
		</tbody>
	</table>
	<?php $this->partial("shared/paginator", array('url' => 'prevtrax/index/', 'param' => NULL)) ?>
</div>
