<div class="banner-content">
	<div class="container">
		<div class="row">
			<div class="col-md-7 col-sm-7">
				<h1><strong>提升</strong> 商业价值</h1>
				<p>随时随地获取您想要的！</p>
				<ul class="banner-list">
					<li><i class="glyphicon glyphicon-ok"></i>随时随刻，便捷</li>
					<li><i class="glyphicon glyphicon-ok"></i>想你所想，智能</li>
					<li><i class="glyphicon glyphicon-ok"></i>多重防护，安全</li>
					<li><i class="glyphicon glyphicon-ok"></i>全面的数据统计分析，高效</li>
					<li><i class="glyphicon glyphicon-ok"></i>顺应潮流，开放</li>
				</ul>
			</div>
		</div>
	</div>
</div>
